# Generated by Django 4.2.26 on 2025-11-12 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(9999999)]
            ),
        ),
    ]
