# Generated by Django 4.2.26 on 2025-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="priority",
            field=models.IntegerField(
                default=999, help_text="ترتیب نمایش در صفحه اصلی (عدد کمتر= بالاتر)"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="priority",
            field=models.IntegerField(
                default=999, help_text="ترتیب نمایش در صفحه اصلی (عدد کمتر= بالاتر)"
            ),
        ),
    ]
